apiVersion: v1
kind: ConfigMap
metadata:
  name: backstack-app-config
  namespace: backstage
data:
  app-config.extra.yaml: |
    app:
      baseUrl: https://${BACKSTAGE_HOST}
      title: BACK Stack IDP
      support:
        url: https://github.com/back-stack/showcase/issues # Used by common ErrorPage
        items: # Used by common SupportButton component
          - title: Issues
            icon: github
            links:
              - url: https://github.com/back-stack/showcase/issues
                title: GitHub Issues
          - title: CNCF Slack Channel
            icon: chat
            links:
              - url: https://cloud-native.slack.com/archives/C066BJRLS4B
                title: '#backstack'
    auth: {}
      # TODO: https://github.com/nirmata/backstack-internal/issues/34 figure out how to best allow for setting these: https://github.com/backstage/backstage/blob/16ef9e59e5c735f13b3468abd52748321fd55937/app-config.yaml#L314
    backend:
      baseUrl: https://${BACKSTAGE_HOST}
      cors:
        credentials: true
        methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
        origin: http://localhost:3000
      csp:
        connect-src:
        - '''self'''
        - 'http:'
        - 'https:'
      database:
        client: better-sqlite3
        connection: ':memory:'
      listen:
        port: 7007
    catalog:
      locations:
      - rules:
        - allow: [Group, User]
        target: ${REPOSITORY}/blob/main/backstage-org.yaml
        type: url
      - rules:
        - allow: [Component, API, Resource, Template, System]
        target: ${REPOSITORY}/blob/main/backstage-catalog-info.yaml
        type: url
    integrations:
      github:
      - host: github.com
        token: ${GITHUB_TOKEN}
      ### Example for how to add your GitHub Enterprise instance using the API:
      # - host: ghe.example.net
      #   apiBaseUrl: https://ghe.example.net/api/v3
      #   token: ${GHE_TOKEN}
      ### Example for how to add your GitHub Enterprise instance using raw HTTP fetches (token is optional):
      # - host: ghe.example.net
      #   rawBaseUrl: https://ghe.example.net/raw
      #   token: ${GHE_TOKEN}
      # gitlab:
      #   - host: gitlab.com
      #     token: ${GITLAB_TOKEN}
      ### Example for how to add a bitbucket cloud integration
      # bitbucketCloud:
      #   - username: ${BITBUCKET_USERNAME}
      #     appPassword: ${BITBUCKET_APP_PASSWORD}
      ### Example for how to add your bitbucket server instance using the API:
      # - host: server.bitbucket.com
      #   apiBaseUrl: server.bitbucket.com
      #   username: ${BITBUCKET_SERVER_USERNAME}
      #   appPassword: ${BITBUCKET_SERVER_APP_PASSWORD}
      # azure:
      #   - host: dev.azure.com
      #     token: ${AZURE_TOKEN}
      #  googleGcs:
      #    clientEmail: 'example@example.com'
      #    privateKey: ${GCS_PRIVATE_KEY}
      # awsS3:
      #   - endpoint: ${AWS_S3_ENDPOINT}
      #     accessKeyId: ${AWS_ACCESS_KEY_ID}
      #     secretAccessKey: ${AWS_SECRET_ACCESS_KEY}
    kubernetes:
      clusterLocatorMethods:
      - type: catalog
      serviceLocatorMethod:
        type: multiTenant
    organization:
      name: BACK Stack
    proxy: null
    scaffolder: null
    techdocs:
      builder: local
      generator:
        runIn: docker
      publisher:
        type: local
    vault:
      baseUrl: http://vault.vault.svc:8200
      kvVersion: "2"
      publicUrl: https://${VAULT_HOST}
      secretEngine: secret
      token: ${VAULT_TOKEN}
