apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clusters-from-hub
  namespace: argocd
spec:
  project: default
  source:
    repoURL: ${REPOSITORY} # patched
    path: demo/clusters
    targetRevision: HEAD
  destination:
    name: hub
    namespace: default # needs to be configurable
