apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps-from-hub
  namespace: argocd
spec:
  project: default
  source:
    repoURL: ${REPOSITORY} # patched
    path: demo/applications
    targetRevision: HEAD
  destination:
    name: hub
    namespace: default #this needs to be configurable
