configs:
  params:
    server.insecure: true
  cm:
    dex.config: |
      connectors:
      - config:
          issuer: https://accounts.google.com
          clientID: {ARGOCD_GOOGLE_AUTH_CLIENT_ID}
          clientSecret: ${ARGOCD_GOOGLE_AUTH_CLIENT_SECRET}
        type: oidc
        id: google
        name: Google
    exec.enabled: "false"
    server.rbac.log.enforce.enable: "false"
    application.resourceTrackingMethod: annotation
    # url: added as patch set
server:
  deploymentAnnotations:
    backstage.io/kubernetes-id: argocd-service
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
      cert-manager.io/cluster-issuer: selfsigned-cluster-issuer
    hosts:
    - hostname # patched
  ingressGrpc:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
      cert-manager.io/cluster-issuer: selfsigned-cluster-issuer
    hosts:
    - grpc.hostname # patched
