apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${{ values.application_name }}
  namespace: argocd
spec:
  project: default
  source:
    repoURL: ${{ values.application_source }}
    path: ${{ values.application_source_path }}
    targetRevision: HEAD
    kyverno_custom_repository: ${{ values.custom_kyverno_policies }}
  destination:
    name: ${{ values.cluster_id }}
    namespace: default
