apiVersion: pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: backstack
spec:
  package: ${CROSSPLANE_IMAGE}:${CROSSPLANE_IMAGE_TAG}
  skipDependencyResolution: true
  packagePullPolicy: Always
