apiVersion: kyverno.io/v2beta1
kind: PolicyException
metadata:
  name: crossplane-system-operation
  namespace: crossplane-system
spec:
  exceptions:
  - policyName: disallow-capabilities-strict
    ruleNames:
    - autogen-require-drop-all
  - policyName: require-run-as-nonroot
    ruleNames:
    - autogen-run-as-non-root
  - policyName: restrict-seccomp-strict
    ruleNames:
    - autogen-check-seccomp-strict
  match:
    any:
    - resources:
        kinds:
        - Pod
        - Deployment
        namespaces:
        - crossplane-system
        names:
        # TODO: this should be more targeted than blanket *
        - crossplane*
