server:
  dev:
    enabled: true
  ui:
    enabled: true
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: selfsigned-cluster-issuer
    hosts:
    - host: ${VAULT_HOST} # patched
    tls:
    - hosts:
      - ${VAULT_HOST} # patched
      secretName: vault-tls
  volumes:
  - name: crossplane-ess-plugin
    configMap:
      name: crossplane-ess-plugin
      items:
      - key: run.sh
        path: run.sh
        mode: 511
  volumeMounts:
  - name: crossplane-ess-plugin
    mountPath: /vault/userconfig/crossplane-ess-plugin
  postStart:
  - /bin/sh
  - -c
  - /vault/userconfig/crossplane-ess-plugin/run.sh
