apiVersion: kyverno.io/v2beta1
kind: PolicyException
metadata:
  name: ingress-nginx-kind-host-ports
  namespace: ingress-nginx
spec:
  exceptions:
  - policyName: disallow-host-ports
    ruleNames:
    - autogen-host-ports-none
  match:
    any:
    - resources:
        kinds:
        - Pod
        - Deployment
        namespaces:
        - ingress-nginx
        names:
        - ingress-nginx*
