ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: selfsigned-cluster-issuer
  tls:
    enabled: true
    secretName: backstage-tls
backstage:
  image:
    registry: ${REGISTRY}
    repository: ${BACKSTAGE_IMAGE} #needs to be patched in
    tag: latest
    pullPolicy: Always
  extraEnvVarsSecrets:
  - backstage
