apiVersion: kubernetes.crossplane.io/v1alpha1
kind: Object
spec:
  forProvider:
    manifest:
      apiVersion: cert-manager.io/v1
      kind: ClusterIssuer
      metadata:
        name: selfsigned-cluster-issuer
      spec:
        selfSigned: {}
