apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kyverno
  namespace: argocd
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          clusterType: spoke
  template:
    metadata:
      name: '{{name}}-kyverno'
      annotations:
        argocd.argoproj.io/sync-wave: "-1"
    spec:
      project: "default"
      source:
        repoURL: https://github.com/kyverno/kyverno
        targetRevision: release-1.11 # TODO: https://github.com/nirmata/backstack-internal/issues/33 need a way to set and control this
        path: charts/kyverno
        helm:
          releaseName: "{{name}}-kyverno"
      destination:
        server: '{{server}}'
        namespace: kyverno
      syncPolicy:
        syncOptions:
        - Replace=true
        - CreateNamespace=true
        automated:
          selfHeal: true
        retry:
          limit: 30
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m0s
