apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps-from-hub
  namespace: argocd
spec:
  project: default
  source:
    repoURL: ${REQUEST_REPOSITORY}
    path: application-requests
    targetRevision: HEAD
  destination:
    name: hub
    namespace: default # TODO: https://github.com/nirmata/backstack-internal/issues/30 needs to be configurable
