apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clusters-from-hub
  namespace: argocd
spec:
  project: default
  source:
    repoURL: ${REQUEST_REPOSITORY}
    path: cluster-requests
    targetRevision: HEAD
  destination:
    name: hub
    namespace: default # TODO: needs to be configurable
