apiVersion: kyverno.io/v2beta1
kind: PolicyException
metadata:
  name: vault-operation
  namespace: vault
spec:
  exceptions:
  - policyName: disallow-capabilities-strict
    ruleNames:
    - require-drop-all
    - autogen-require-drop-all
  - policyName: restrict-seccomp-strict
    ruleNames:
    - check-seccomp-strict
    - autogen-check-seccomp-strict
  match:
    any:
    - resources:
        kinds:
        - Pod
        - Deployment
        - ReplicaSet
        - StatefulSet
        namespaces:
        - vault
        names:
        # TODO: this should be more targeted than blanket *
        - vault*
