apiVersion: v1
kind: ConfigMap
metadata:
  name: crossplane-ess-plugin
  namespace: vault
data:
  run.sh: |
    sleep 4
    vault auth enable kubernetes
    vault write auth/kubernetes/config token_reviewer_jwt="$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" kubernetes_host="https://$KUBERNETES_PORT_443_TCP_ADDR:443" kubernetes_ca_cert=@/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    vault policy write crossplane - <<EOF
      path "secret/data/*" {
        capabilities = ["create", "read", "update", "delete"]
      }
      path "secret/metadata/*" {
        capabilities = ["create", "read", "update", "delete"]
      }
    EOF
    vault write auth/kubernetes/role/crossplane bound_service_account_names="*" bound_service_account_namespaces=crossplane-system policies=crossplane ttl=24h
