name: Validate applications workflow

on:
  pull_request:
    branches:
      - main
    paths:
      - "demo/applications/*.yaml"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job to validate applications
  validate-application-yaml:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout template
        uses: actions/checkout@v4

      - name: Checkout Kyverno PSS Restricted Policies Repo
        uses: actions/checkout@v4
        repository: git@github.com:kyverno/policies.git

      - name: Install Kyverno CLI
        uses: kyverno/action-install-cli@v0.2.0

      - name: Check Kyverno install
        run: kyverno version

      - name: Validate application
        run: |
          kyverno apply ./policies/pod-security/restricted -b main  --resource=./demo/applications
