name: Validate cluster claim workflow

on:
  pull_request:
    branches:
      - main
    paths:
      - "demo/clusters/*.yaml"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job to generate the cluster claim yaml
  validate-cluster-yaml:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout local repo
        uses: actions/checkout@v4

      - name: Checkout BACK Stack Policy Repo
        uses: actions/checkout@v4
        repository: https://github.com/nirmata/backstack-internal-policies
        token:

      - name: Install Kyverno CLI
        uses: kyverno/action-install-cli@v0.2.0

      - name: Check Kyverno install
        run: kyverno version

      - name: Validate cluster claim
        run: |
          kyverno apply ./kyverno/policies/crossplane -b main  --resource=./demo/clusters
